#!/usr/bin/env bash
# This script displays "Best School" 10 times using 'while' loop
# At the 4th loop display 'bad luck' and the 8th loop display 'good luck'

const="Best School"

(( count = 1 ))


while [ "$count" -le 10 ]
do
	if [ "$count" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$count" -eq 8 ]
	then
		echo "good luck"
	else
		echo "$const"
	fi

	(( count++ ))
done
