#!/usr/bin/env bash
# Debugging a nginx web server in less than 7 lines
pkill apache2
chmod u=rw,g=rw,o=rw /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i '1s/^/user nginx;\n/' /etc/nginx/nginx.conf # This line is not necessary but could be required for future debugging
su - nginx -c "service nginx start" # or sudo -H -u nginx bash -c "service nginx start"
